CREATE DATABASE STOCKDB;


CREATE TABLE STOCK (
  TRANSCT_DATE DATE,
  SYMBOL VARCHAR(45) NOT NULL,
  OPEN DOUBLE  NOT NULL,
  CLOSE DOUBLE  NOT NULL,
  LOW DOUBLE  NOT NULL,
  HIGH DOUBLE  NOT NULL,
  VOLUME DOUBLE  NOT NULL

  );
  

SELECT SYMBOL FROM STOCK WHERE SYMBOL='WLTW';

select * FROM STOCK WHERE SYMBOL LIKE '\tAAP\t';

SELECT DISTINCT replace(SYMBOL, '\t','') FROM STOCK;

UPDATE STOCK SET `SYMBOL` = REPLACE(`SYMBOL`, '\t', '' );


SELECT DISTINCT SYMBOL FROM STOCK;


SELECT COUNT(*) FROM STOCK; 	
  
 DROP TABLE STOCK;
  
UPDATE STOCK SET VOLUME = replace(SYMBOL, '\t', '');

UPDATE STOCK SET SYMBOL = substring(SYMBOL, -1) WHERE SYMBOL like '\t%';
  

SELECT COUNT(*) AS COUNT FROM STOCK; 
  
SELECT  * FROM STOCK WHERE SYMBOL = 'WLTW'
  